spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name : com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

prop:
  upload-folder: D:\IDEAwork\travel\upload\\
server:
  port: 8086

mybatis:
  configuration:
    map-underscore-to-camel-case: true